//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22cntt3_pvv_project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIM()
        {
            this.COMMENTS = new HashSet<COMMENTS>();
            this.FAVORITES = new HashSet<FAVORITES>();
        }
    
        public int MaPhim { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string TenPhim { get; set; }
        public string The_loai { get; set; }
        public Nullable<int> Nam_sx { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTS> COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORITES> FAVORITES { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
